version: "3.9"

services:
  database:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mytrophy_db"
      MYSQL_ROOT_HOST: 'root'
      MYSQL_ROOT_PASSWORD:
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
  backend:
    container_name: mytrophy_backend
    build:
      dockerfile: Dockerfile
    #    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.64.52.132:3306/mytrophy_db
      SPRING_DATASOURCE_USERNAME: "mytrophy"
      SPRING_DATASOURCE_PASSWORD: "mytrophy"
    ports:
      - "8080:8080"
    depends_on:
      - database
#  frontend:
#    build:
#      context: /frontend
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "3000:3000"
#    depends_on:
#      - database